name: Deploy Backend

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          password: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/4x4/4x4-dashboard
            git pull origin main
            npm install
            npm run build
            pm2 restart all
